    dist: trusty
    language: node_js
    node_js:
    - stable
    script:
    - npm run coverage
    branches:
      only: development
    notifications:
      email:
        recipients:
        - 530606349@qq.com      # change to your own address
        - 20082474@mail.wit.ie    # uae other (optional)
        on_success: never        # default: change
        on_failure: always       # default: always